### ISSUE TITLE
Pyocd failed cause of missing dependencies in docker

### ISSUE THREAD

**Issue by majunkier** [zephyrproject-rtos/docker-image#130]
When i run docker(v 0.24.7) image based on instruction, i got error during run pyocd command :

```
Traceback (most recent call last):
  File "/usr/local/bin/pyocd", line 5, in <module>
    from pyocd.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/pyocd/__init__.py", line 21, in <module>
    from . import gdbserver
  File "/usr/local/lib/python3.8/dist-packages/pyocd/gdbserver/__init__.py", line 17, in <module>
    from .gdbserver import GDBServer
  File "/usr/local/lib/python3.8/dist-packages/pyocd/gdbserver/gdbserver.py", line 41, in <module>
    from ..rtos import RTOS
  File "/usr/local/lib/python3.8/dist-packages/pyocd/rtos/__init__.py", line 29, in <module>
    load_plugin_classes_of_type('pyocd.rtos', RTOS, ThreadProvider)
  File "/usr/local/lib/python3.8/dist-packages/pyocd/core/plugin.py", line 97, in load_plugin_classes_of_type
    plugin = entry_point.load()()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (six 1.14.0 (/usr/lib/python3/dist-packages), Requirement.parse('six<2.0,>=1.15.0'))
```

**Comment by stephanosio** [comment]
Should be fixed by https://github.com/zephyrproject-rtos/docker-image/pull/129
